name: Run Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - '*'

jobs:
  run-test:
    environment: test-environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Install dependencies
        run: |
          python -m pip install boto3 pandas openpyxl pytest --user
          python -m pip install google-api-python-client --user
          python -m pip install google-auth-httplib2 --user
          python -m pip install google-auth-oauthlib --user
      - name: Run tests
        run: |
          echo ${{ secrets.GOOGLE_SVC_ACC_KEY }} | base64 -d > .gtest.json
          python -m pytest
          rm .gtest.json
